version: '3'
services:
  workspace:
    container_name: workspace-cmdk
    build: ./dev/workspace
    env_file: ./dev/workspace/env.list
    ports:
      - '3000:3000'
      - '3001:3001'
      - '4000:4000'
      - '8080:8080'
    volumes:
      - './.turbo:/cmdk/.turbo'
      - './.prettierrc:/cmdk/.prettierrc'
      - './bin:/cmdk/bin'
      - './meta:/cmdk/meta'
      - './apps:/cmdk/apps'
      - './docs:/cmdk/docs'
      - './packages:/cmdk/packages'
      - './node_modules:/cmdk/node_modules'
      - './package.json:/cmdk/package.json'
      - './yarn.lock:/cmdk/yarn.lock'
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    depends_on:
      - workspace
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
      - ./apps/external:/var/www/external
  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
      - ./dev/certbot/scripts:/scripts
    entrypoint: sh /scripts/challenge.sh
